server:
  port: 8080

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/auth?useSSL=false&allowPublicKeyRetrieval=true"
    username: root
    password: thang123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
jwt:
  signerKey: "UfDISbD7S+7ZKexMy82qISu0BlUuf9l/Oq201VoK5eoN5nKC6UXhc4hRHCyZ/Mu/"
  valid-duration: 5000 #second
  refreshable-duration: 5000 #second


security:
  users:
    - username: admin
      password: "{noop}123456" # {noop} nếu không dùng password encoder
      roles: ADMIN
    - username: user1
      password: "{noop}userpass"
      roles: USER