server:
  port: 8082

spring:
  datasource:
    url: "jdbc:mysql://mysql:3306/auth?useSSL=false&allowPublicKeyRetrieval=true"
    username: root
    password: thang123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  kafka:
    bootstrap-servers: kafka:9092
