server:
  port: 8080

spring:
  cloud:
    gateway:
      global-cors:
        cors-configurations:
          '[/**]':
            allowed-origins: 
              - "http://localhost:3000"
              - "http://localhost:5173"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowed-headers: "*"
            allow-credentials: true
            max-age: 3600
      
      routes:
        - id: auth-service
          uri: http://auth-service:8081
          predicates:
            - Path=/auth-service/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: authServiceCircuitBreaker
                fallbackUri: forward:/fallback/auth-service
        
        - id: account-service
          uri: http://account-service:8082
          predicates:
            - Path=/account-service/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: accountServiceCircuitBreaker
                fallbackUri: forward:/fallback/account-service
        
        - id: menu-service
          uri: http://menu-service:8083
          predicates:
            - Path=/menu-service/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: menuServiceCircuitBreaker
                fallbackUri: forward:/fallback/menu-service

        - id: audit-service
          uri: http://audit-service:8084
          predicates:
            - Path=/audit-service/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: auditServiceCircuitBreaker
                fallbackUri: forward:/fallback/audit-service

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        slowCallRateThreshold: 100
        slowCallDurationThreshold: 60000
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        recordExceptions:
          - java.io.IOException
          - java.util.concurrent.TimeoutException
          - org.springframework.web.client.ResourceAccessException
    instances:
      authServiceCircuitBreaker:
        baseConfig: default
        failureRateThreshold: 30
        waitDurationInOpenState: 5000
      accountServiceCircuitBreaker:
        baseConfig: default
        failureRateThreshold: 40
        waitDurationInOpenState: 8000
      menuServiceCircuitBreaker:
        baseConfig: default
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
  timelimiter:
    configs:
      default:
        timeoutDuration: 5s
    instances:
      authServiceCircuitBreaker:
        timeoutDuration: 3s
      accountServiceCircuitBreaker:
        timeoutDuration: 4s
      menuServiceCircuitBreaker:
        timeoutDuration: 5s
