server:
  port: 8081

spring:
  datasource:
    url: "jdbc:mysql://mysql:3306/auth?useSSL=false&allowPublicKeyRetrieval=true"
    username: root
    password: thang123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

jwt:
  valid-duration: 5000 #second
  refreshable-duration: 5000 #second

security:
  users:
    - username: admin
      password: "{noop}123456"
      roles: ADMIN
    - username: user1
      password: "{noop}userpass"
      roles: USER

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.web.FilterChainProxy: DEBUG
    org.springframework.security.web.access.intercept.AuthorizationFilter: TRACE
