server:
  port: 8080

spring:
  cloud:
    gateway:
      global-cors:
        cors-configurations:
          '[/**]':
            allowed-origins: 
              - "http://localhost:3000"
              - "http://localhost:5173"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowed-headers: "*"
            allow-credentials: true
            max-age: 3600
      
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=0
            - name: CircuitBreaker
              args:
                name: authServiceCircuitBreaker
                fallbackUri: forward:/fallback/auth-service
        
        - id: account-service
          uri: http://localhost:8082
          predicates:
            - Path=/users/**,/roles/**,/permissions/**
          filters:
            - StripPrefix=0
            - name: CircuitBreaker
              args:
                name: accountServiceCircuitBreaker
                fallbackUri: forward:/fallback/account-service
        
        - id: menu-service
          uri: http://localhost:8083
          predicates:
            - Path=/menus/**
          filters:
            - StripPrefix=0
            - name: CircuitBreaker
              args:
                name: menuServiceCircuitBreaker
                fallbackUri: forward:/fallback/menu-service

        - id: audit-service
          uri: http://localhost:8084
          predicates:
            - Path=/audit-logs/**
          filters:
            - StripPrefix=0
            - name: CircuitBreaker
              args:
                name: menuServiceCircuitBreaker
                fallbackUri: forward:/fallback/menu-service

#      //Global filter check rate limit .Có redis thì mới bật
#      default-filters:
#        - name: RequestRateLimiter
#          args:
#            redis-rate-limiter:
#              replenishRate: 10
#              burstCapacity: 20
#              requestedTokens: 1
#        - AddRequestHeader=X-Gateway-Request, ApiGateway
#        - AddResponseHeader=X-Gateway-Response, ApiGateway

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        slowCallRateThreshold: 100
        slowCallDurationThreshold: 60000
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        recordExceptions:
          - java.io.IOException
          - java.util.concurrent.TimeoutException
          - org.springframework.web.client.ResourceAccessException
    instances:
      authServiceCircuitBreaker:
        baseConfig: default
        failureRateThreshold: 30
        waitDurationInOpenState: 5000
      accountServiceCircuitBreaker:
        baseConfig: default
        failureRateThreshold: 40
        waitDurationInOpenState: 8000
      menuServiceCircuitBreaker:
        baseConfig: default
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
  timelimiter:
    configs:
      default:
        timeoutDuration: 5s
    instances:
      authServiceCircuitBreaker:
        timeoutDuration: 3s
      accountServiceCircuitBreaker:
        timeoutDuration: 4s
      menuServiceCircuitBreaker:
        timeoutDuration: 5s
