server:
  port: 8080

spring:
  cloud:
    gateway:
      global-cors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "http://localhost:3000"
              - "http://localhost:5173"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowed-headers: "*"
            allow-credentials: true
            max-age: 3600

      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth-service/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: authServiceCircuitBreaker
                fallbackUri: forward:/fallback/auth-service

        - id: account-service
          uri: http://localhost:8082
          predicates:
            - Path=/account-service/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: accountServiceCircuitBreaker
                fallbackUri: forward:/fallback/account-service

        - id: menu-service
          uri: http://localhost:8083
          predicates:
            - Path=/menu-service/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: menuServiceCircuitBreaker
                fallbackUri: forward:/fallback/menu-service

        - id: audit-service
          uri: http://localhost:8084
          predicates:
            - Path=/audit-service/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: auditServiceCircuitBreaker
                fallbackUri: forward:/fallback/audit-service
